# deploy_cfg.ini  （和可执行文件同目录）
# 说明：简单 key=value 配置，不依赖第三方库。布尔值用 true/false，小写。

use_map=false
model_path_map=./model_lite_nchw.ms
model_path_nomap=./network_lite_no_map_v0.ms
image_path_map=./map.png
image_size_map=64
image_size_nomap=64